version: '3.8'

services:
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    networks:
      - greenland

  redis:
    image: redis
    ports:
      - '6379:6379'
    networks:
      - greenland


networks:
  greenland:
    driver: bridge

volumes:
  mongodb_data:
  mongodb_config: