export const NOTIFICATION_JOB_NAMES = {
  NOTIFICATION_EMAIL: 'NOTIFICATION_EMAIL',
  NOTIFICATION_PUSH: 'NOTIFICATION_PUSH',
  NOTIFICATION_APP: 'NOTIFICATION_APP',
  NOTIFICATION_MESSAGES: 'NOTIFICATION_MESSAGES',
};
